/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DesignSystemBadgesAlertsRouteImport } from './routes/design-system/badges-alerts'
import { Route as DesignSystemButtonRouteImport } from './routes/design-system/button'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemBadgesAlertsRoute =
  DesignSystemBadgesAlertsRouteImport.update({
    id: '/design-system/badges-alerts',
    path: '/design-system/badges-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignSystemButtonRoute = DesignSystemButtonRouteImport.update({
  id: '/design-system/button',
  path: '/design-system/button',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/design-system/badges-alerts': typeof DesignSystemBadgesAlertsRoute
  '/design-system/button': typeof DesignSystemButtonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/design-system/badges-alerts': typeof DesignSystemBadgesAlertsRoute
  '/design-system/button': typeof DesignSystemButtonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/design-system/badges-alerts': typeof DesignSystemBadgesAlertsRoute
  '/design-system/button': typeof DesignSystemButtonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/design-system/badges-alerts' | '/design-system/button'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/design-system/badges-alerts' | '/design-system/button'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/design-system/badges-alerts'
    | '/design-system/button'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DesignSystemBadgesAlertsRoute: typeof DesignSystemBadgesAlertsRoute
  DesignSystemButtonRoute: typeof DesignSystemButtonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system/badges-alerts': {
      id: '/design-system/badges-alerts'
      path: '/design-system/badges-alerts'
      fullPath: '/design-system/badges-alerts'
      preLoaderRoute: typeof DesignSystemBadgesAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system/button': {
      id: '/design-system/button'
      path: '/design-system/button'
      fullPath: '/design-system/button'
      preLoaderRoute: typeof DesignSystemButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DesignSystemBadgesAlertsRoute: DesignSystemBadgesAlertsRoute,
  DesignSystemButtonRoute: DesignSystemButtonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
