/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminAjustesRouteImport } from './routes/_admin/ajustes'
import { Route as AdminArquivosRouteImport } from './routes/_admin/arquivos'
import { Route as AdminAutomacoesRouteImport } from './routes/_admin/automacoes'
import { Route as AdminPerfilRouteImport } from './routes/_admin/perfil'
import { Route as DesignSystemBadgesAlertsRouteImport } from './routes/design-system/badges-alerts'
import { Route as DesignSystemButtonRouteImport } from './routes/design-system/button'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAjustesRoute = AdminAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArquivosRoute = AdminArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomacoesRoute = AdminAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AdminRoute,
} as any)
const DesignSystemBadgesAlertsRoute =
  DesignSystemBadgesAlertsRouteImport.update({
    id: '/design-system/badges-alerts',
    path: '/design-system/badges-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignSystemButtonRoute = DesignSystemButtonRouteImport.update({
  id: '/design-system/button',
  path: '/design-system/button',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ajustes': typeof AdminAjustesRoute
  '/arquivos': typeof AdminArquivosRoute
  '/automacoes': typeof AdminAutomacoesRoute
  '/perfil': typeof AdminPerfilRoute
  '/design-system/badges-alerts': typeof DesignSystemBadgesAlertsRoute
  '/design-system/button': typeof DesignSystemButtonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ajustes': typeof AdminAjustesRoute
  '/arquivos': typeof AdminArquivosRoute
  '/automacoes': typeof AdminAutomacoesRoute
  '/perfil': typeof AdminPerfilRoute
  '/design-system/badges-alerts': typeof DesignSystemBadgesAlertsRoute
  '/design-system/button': typeof DesignSystemButtonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/ajustes': typeof AdminAjustesRoute
  '/_admin/arquivos': typeof AdminArquivosRoute
  '/_admin/automacoes': typeof AdminAutomacoesRoute
  '/_admin/perfil': typeof AdminPerfilRoute
  '/design-system/badges-alerts': typeof DesignSystemBadgesAlertsRoute
  '/design-system/button': typeof DesignSystemButtonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ajustes'
    | '/arquivos'
    | '/automacoes'
    | '/perfil'
    | '/design-system/badges-alerts'
    | '/design-system/button'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ajustes'
    | '/arquivos'
    | '/automacoes'
    | '/perfil'
    | '/design-system/badges-alerts'
    | '/design-system/button'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/ajustes'
    | '/_admin/arquivos'
    | '/_admin/automacoes'
    | '/_admin/perfil'
    | '/design-system/badges-alerts'
    | '/design-system/button'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  DesignSystemBadgesAlertsRoute: typeof DesignSystemBadgesAlertsRoute
  DesignSystemButtonRoute: typeof DesignSystemButtonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/ajustes': {
      id: '/_admin/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AdminAjustesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/arquivos': {
      id: '/_admin/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AdminArquivosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/automacoes': {
      id: '/_admin/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AdminAutomacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/perfil': {
      id: '/_admin/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/design-system/badges-alerts': {
      id: '/design-system/badges-alerts'
      path: '/design-system/badges-alerts'
      fullPath: '/design-system/badges-alerts'
      preLoaderRoute: typeof DesignSystemBadgesAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system/button': {
      id: '/design-system/button'
      path: '/design-system/button'
      fullPath: '/design-system/button'
      preLoaderRoute: typeof DesignSystemButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAjustesRoute: typeof AdminAjustesRoute
  AdminArquivosRoute: typeof AdminArquivosRoute
  AdminAutomacoesRoute: typeof AdminAutomacoesRoute
  AdminPerfilRoute: typeof AdminPerfilRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAjustesRoute: AdminAjustesRoute,
  AdminArquivosRoute: AdminArquivosRoute,
  AdminAutomacoesRoute: AdminAutomacoesRoute,
  AdminPerfilRoute: AdminPerfilRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  DesignSystemBadgesAlertsRoute: DesignSystemBadgesAlertsRoute,
  DesignSystemButtonRoute: DesignSystemButtonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
