/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminArquivosRouteImport } from './routes/_admin/arquivos'
import { Route as AdminAutomacoesRouteImport } from './routes/_admin/automacoes'
import { Route as AdminCategoriasRouteImport } from './routes/_admin/categorias'
import { Route as AdminEmpresasRouteImport } from './routes/_admin/empresas'
import { Route as AdminPerfilRouteImport } from './routes/_admin/perfil'
import { Route as AdminRbacRouteImport } from './routes/_admin/rbac'
import { Route as AdminUsuariosRouteImport } from './routes/_admin/usuarios'
import { Route as AdminAutomacoesIndexRouteImport } from './routes/_admin/automacoes.index'
import { Route as AdminAutomacoesNovaRouteImport } from './routes/_admin/automacoes.nova'
import { Route as AdminEmpresasIndexRouteImport } from './routes/_admin/empresas.index'
import { Route as AdminEmpresasNovaRouteImport } from './routes/_admin/empresas.nova'
import { Route as AdminAutomacoesIdEditarRouteImport } from './routes/_admin/automacoes.$id.editar'
import { Route as AdminEmpresasIdEditarRouteImport } from './routes/_admin/empresas.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArquivosRoute = AdminArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomacoesRoute = AdminAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRbacRoute = AdminRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomacoesIndexRoute = AdminAutomacoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAutomacoesRoute,
} as any)
const AdminAutomacoesNovaRoute = AdminAutomacoesNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AdminAutomacoesRoute,
} as any)
const AdminEmpresasIndexRoute = AdminEmpresasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEmpresasRoute,
} as any)
const AdminEmpresasNovaRoute = AdminEmpresasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AdminEmpresasRoute,
} as any)
const AdminAutomacoesIdEditarRoute = AdminAutomacoesIdEditarRouteImport.update({
  id: '/$id/editar',
  path: '/$id/editar',
  getParentRoute: () => AdminAutomacoesRoute,
} as any)
const AdminEmpresasIdEditarRoute = AdminEmpresasIdEditarRouteImport.update({
  id: '/$id/editar',
  path: '/$id/editar',
  getParentRoute: () => AdminEmpresasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/arquivos': typeof AdminArquivosRoute
  '/automacoes': typeof AdminAutomacoesRouteWithChildren
  '/categorias': typeof AdminCategoriasRoute
  '/empresas': typeof AdminEmpresasRouteWithChildren
  '/perfil': typeof AdminPerfilRoute
  '/rbac': typeof AdminRbacRoute
  '/usuarios': typeof AdminUsuariosRoute
  '/automacoes/nova': typeof AdminAutomacoesNovaRoute
  '/empresas/nova': typeof AdminEmpresasNovaRoute
  '/automacoes/': typeof AdminAutomacoesIndexRoute
  '/empresas/': typeof AdminEmpresasIndexRoute
  '/automacoes/$id/editar': typeof AdminAutomacoesIdEditarRoute
  '/empresas/$id/editar': typeof AdminEmpresasIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/arquivos': typeof AdminArquivosRoute
  '/categorias': typeof AdminCategoriasRoute
  '/perfil': typeof AdminPerfilRoute
  '/rbac': typeof AdminRbacRoute
  '/usuarios': typeof AdminUsuariosRoute
  '/automacoes/nova': typeof AdminAutomacoesNovaRoute
  '/empresas/nova': typeof AdminEmpresasNovaRoute
  '/automacoes': typeof AdminAutomacoesIndexRoute
  '/empresas': typeof AdminEmpresasIndexRoute
  '/automacoes/$id/editar': typeof AdminAutomacoesIdEditarRoute
  '/empresas/$id/editar': typeof AdminEmpresasIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/arquivos': typeof AdminArquivosRoute
  '/_admin/automacoes': typeof AdminAutomacoesRouteWithChildren
  '/_admin/categorias': typeof AdminCategoriasRoute
  '/_admin/empresas': typeof AdminEmpresasRouteWithChildren
  '/_admin/perfil': typeof AdminPerfilRoute
  '/_admin/rbac': typeof AdminRbacRoute
  '/_admin/usuarios': typeof AdminUsuariosRoute
  '/_admin/automacoes/nova': typeof AdminAutomacoesNovaRoute
  '/_admin/empresas/nova': typeof AdminEmpresasNovaRoute
  '/_admin/automacoes/': typeof AdminAutomacoesIndexRoute
  '/_admin/empresas/': typeof AdminEmpresasIndexRoute
  '/_admin/automacoes/$id/editar': typeof AdminAutomacoesIdEditarRoute
  '/_admin/empresas/$id/editar': typeof AdminEmpresasIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/arquivos'
    | '/automacoes'
    | '/categorias'
    | '/empresas'
    | '/perfil'
    | '/rbac'
    | '/usuarios'
    | '/automacoes/nova'
    | '/empresas/nova'
    | '/automacoes/'
    | '/empresas/'
    | '/automacoes/$id/editar'
    | '/empresas/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/arquivos'
    | '/categorias'
    | '/perfil'
    | '/rbac'
    | '/usuarios'
    | '/automacoes/nova'
    | '/empresas/nova'
    | '/automacoes'
    | '/empresas'
    | '/automacoes/$id/editar'
    | '/empresas/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/arquivos'
    | '/_admin/automacoes'
    | '/_admin/categorias'
    | '/_admin/empresas'
    | '/_admin/perfil'
    | '/_admin/rbac'
    | '/_admin/usuarios'
    | '/_admin/automacoes/nova'
    | '/_admin/empresas/nova'
    | '/_admin/automacoes/'
    | '/_admin/empresas/'
    | '/_admin/automacoes/$id/editar'
    | '/_admin/empresas/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/arquivos': {
      id: '/_admin/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AdminArquivosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/automacoes': {
      id: '/_admin/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AdminAutomacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/categorias': {
      id: '/_admin/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/empresas': {
      id: '/_admin/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/perfil': {
      id: '/_admin/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/rbac': {
      id: '/_admin/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof AdminRbacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/usuarios': {
      id: '/_admin/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/automacoes/': {
      id: '/_admin/automacoes/'
      path: '/'
      fullPath: '/automacoes/'
      preLoaderRoute: typeof AdminAutomacoesIndexRouteImport
      parentRoute: typeof AdminAutomacoesRoute
    }
    '/_admin/automacoes/nova': {
      id: '/_admin/automacoes/nova'
      path: '/nova'
      fullPath: '/automacoes/nova'
      preLoaderRoute: typeof AdminAutomacoesNovaRouteImport
      parentRoute: typeof AdminAutomacoesRoute
    }
    '/_admin/empresas/': {
      id: '/_admin/empresas/'
      path: '/'
      fullPath: '/empresas/'
      preLoaderRoute: typeof AdminEmpresasIndexRouteImport
      parentRoute: typeof AdminEmpresasRoute
    }
    '/_admin/empresas/nova': {
      id: '/_admin/empresas/nova'
      path: '/nova'
      fullPath: '/empresas/nova'
      preLoaderRoute: typeof AdminEmpresasNovaRouteImport
      parentRoute: typeof AdminEmpresasRoute
    }
    '/_admin/automacoes/$id/editar': {
      id: '/_admin/automacoes/$id/editar'
      path: '/$id/editar'
      fullPath: '/automacoes/$id/editar'
      preLoaderRoute: typeof AdminAutomacoesIdEditarRouteImport
      parentRoute: typeof AdminAutomacoesRoute
    }
    '/_admin/empresas/$id/editar': {
      id: '/_admin/empresas/$id/editar'
      path: '/$id/editar'
      fullPath: '/empresas/$id/editar'
      preLoaderRoute: typeof AdminEmpresasIdEditarRouteImport
      parentRoute: typeof AdminEmpresasRoute
    }
  }
}

interface AdminAutomacoesRouteChildren {
  AdminAutomacoesNovaRoute: typeof AdminAutomacoesNovaRoute
  AdminAutomacoesIndexRoute: typeof AdminAutomacoesIndexRoute
  AdminAutomacoesIdEditarRoute: typeof AdminAutomacoesIdEditarRoute
}

const AdminAutomacoesRouteChildren: AdminAutomacoesRouteChildren = {
  AdminAutomacoesNovaRoute: AdminAutomacoesNovaRoute,
  AdminAutomacoesIndexRoute: AdminAutomacoesIndexRoute,
  AdminAutomacoesIdEditarRoute: AdminAutomacoesIdEditarRoute,
}

const AdminAutomacoesRouteWithChildren = AdminAutomacoesRoute._addFileChildren(
  AdminAutomacoesRouteChildren,
)

interface AdminEmpresasRouteChildren {
  AdminEmpresasNovaRoute: typeof AdminEmpresasNovaRoute
  AdminEmpresasIndexRoute: typeof AdminEmpresasIndexRoute
  AdminEmpresasIdEditarRoute: typeof AdminEmpresasIdEditarRoute
}

const AdminEmpresasRouteChildren: AdminEmpresasRouteChildren = {
  AdminEmpresasNovaRoute: AdminEmpresasNovaRoute,
  AdminEmpresasIndexRoute: AdminEmpresasIndexRoute,
  AdminEmpresasIdEditarRoute: AdminEmpresasIdEditarRoute,
}

const AdminEmpresasRouteWithChildren = AdminEmpresasRoute._addFileChildren(
  AdminEmpresasRouteChildren,
)

interface AdminRouteChildren {
  AdminArquivosRoute: typeof AdminArquivosRoute
  AdminAutomacoesRoute: typeof AdminAutomacoesRouteWithChildren
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminEmpresasRoute: typeof AdminEmpresasRouteWithChildren
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminRbacRoute: typeof AdminRbacRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArquivosRoute: AdminArquivosRoute,
  AdminAutomacoesRoute: AdminAutomacoesRouteWithChildren,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminEmpresasRoute: AdminEmpresasRouteWithChildren,
  AdminPerfilRoute: AdminPerfilRoute,
  AdminRbacRoute: AdminRbacRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
